site_name: ККТ ОНЛАЙН 54-ФЗ Инструкция
nav:
  - Домашняя: README.md
theme: jekyll-theme-slate
extra:
  search:
    language: 'ru'
  social:
    - type: 'github'
      link: 'https://github.com/andrei-karpov'
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true

site_url: 'https://otymko.github.io/1c_kkt_54fz'
repo_name: 'andrei-karpov/1c_kkt_54fz'
repo_url: 'https://github.com/andrei-karpov/1c_kkt_54fz'
edit_uri: 'edit/develop/docs'
