name: GitHub Pages

on:
  push:
    branches:
    - main
    paths:
    - 'docs/**'
    - 'mkdocs.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
          python-version: 3.x

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install mkdocs pygments-bsl markdown mkdocs-material mkdocs-rss-plugin mkdocs-minify-plugin mkdocs-with-pdf pygments pymdown-extensions babel colorama paginate mkdocs-sitemap-plugin
    
    - name: Dowload latest GitHub Pages
      run: |
        wget https://github.com/${{ github.repository }}/archive/gh-pages.zip || true
        unzip gh-pages.zip || true

    - name: Save latest Master
      if: github.ref == 'refs/heads/main'
      run: |
        mkdir public
        cp -R ${GITHUB_REPOSITORY#*/}-gh-pages/. public || true
        rm -rf public/dev || true
        mkdir public/dev

    - name: Build Russian
      run: |
        mkdir temp
        cp mkdocs.yml temp
        cp -R docs/. temp/docs
        cd temp
        mkdocs build
    
    - name: Public Russian master
      if: github.ref == 'refs/heads/main'
      run: |
        cp -R temp/site/. public
    
    - name: Clean temp
      run: rm -rf temp
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.5.0
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
